name: Manual Test e2e

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run API and Frontend
        run: |
          docker run -d -p 3001:3000 hangman-api
          docker run -d -p 8080:8080 -e API_URL=http://localhost:3001 hangman-front

      - name: Run E2E Tests
        run: |
          cd hangman-e2e/e2e
          npm run open
