name: Manual E2E Test

on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start API
        run: docker run -d -p 3001:3000 jaimesalas/hangman-api

      - name: Start Frontend
        run: docker run -d -p 8080:8080 -e API_URL=http://localhost:3001 jaimesalas/hangman-front

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run open
          working-directory: hangman-e2e/e2e
