name: Manual E2E Test Workflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Run Docker Compose
        run: |
          docker-compose build
          docker-compose up -d

      - name: Run E2E Tests
        run: |
          cd hangman-e2e/e2e
          npm run open
